#!/bin/sh
lb config noauto \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free" \
    --mirror-bootstrap http://ftp.fr.debian.org/debian/ \
    --mirror-binary http://ftp.fr.debian.org/debian/ \
    "${@}"
